version: 0.2
phases:
  install:
    runtime-versions:
        nodejs: 12
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - node -v
      - npm -v
      - npm install
  build:
    commands:
      - echo Dev Build started on `date`
      - npm run build
  post_build:
    commands:
      - aws s3 rm --recursive s3://${DEPLOY_BUCKET_NAME}
      - cd public && aws s3 sync . s3://${DEPLOY_BUCKET_NAME}
      - aws cloudfront create-invalidation --distribution-id ${DISTRIBUTION_ID} --paths "/*"
artifacts:
  files:
    - '**/*'
  base-directory: public
